### ISSUE TITLE
sftp details for Daniel

### ISSUE THREAD

**Issue by mrchristian** [consortium/traces_on_mcluhan#13]
Hi J,

Daniel needs sftp details for mcluhan.consortium.io and for the workshop hybrid-player-workshop.consortium.io (or something of the like).

Thanks

S

**Comment by djavco** [comment]
I have them for Mcluhan I just need a new subdomain for your workshop with sftp details

Thanks
Daniel

## 

Daniel Jackson

Avco Productions Ltd
13 Gibraltar Walk, London E2 7LH
http://www.avco.com http://www.avco.com/

Studio:  +44 (0)20 7613 0089
Mobile:  +44 (0) 7958 353 421
daniel@avco.com mailto:tina@avco.com

Avco Productions Limited is Registered in England No. 3401782

## All Information contained within this email and attached document(s) is for the attention of the addressee(s) only, is strictly confidential and is covered by the relevant copyright and moral rights protections.

**Comment by mrchristian** [comment]
Hi D,

I think the current ones we have are out of date. We have been moving hosting and I was uploading some files yesterday and then realised this morning when I check on the site that its not updating. Johannes will give you new details for both Monday AM, first thing.

Thanks

Simon
