### ISSUE TITLE
Google tracking code on web site https://mcluhan.consortium.io/

### ISSUE THREAD

**Issue by mrchristian** [consortium/traces_on_mcluhan#14]
Hi J,

Can you add this to the https://mcluhan.consortium.io/ site please, on the home page and on https://mcluhan.consortium.io/hybridlecture

UA-47101218-4

Thanks

S

**Comment by dreh23** [comment]
code is in place. I'll have to wait until password restriction is gone.

**Comment by mrchristian** [comment]
Hi J

I am not seeing the tracking code on the HTML for the web site, UA-47101218-4. Did you add it?

Thanks

S

**Comment by dreh23** [comment]
I did, but just on the index that is in old. I added it now to the new index.
Should work.
