### ISSUE TITLE
Amara text markup

### ISSUE THREAD

**Issue by mrchristian** [consortium/traces_on_mcluhan#3]
Hi,

I only just notices that Amara allows for text markup for things like italic. I have not used this as I'm unsure what is good practice for captions and second it's too late in the day.

Anyway noted for later and it might be worth keeping an eye on an _itlaic_ and see how the come out in our captions.

Thanks

Simon

**Comment by djavco** [comment]
Great I’ll use this
D

## 

Daniel Jackson

Avco Productions Ltd
13 Gibraltar Walk, London E2 7LH
http://www.avco.com http://www.avco.com/

Studio:  +44 (0)20 7613 0089
Mobile:  +44 (0) 7958 353 421
daniel@avco.com mailto:tina@avco.com

Avco Productions Limited is Registered in England No. 3401782

## All Information contained within this email and attached document(s) is for the attention of the addressee(s) only, is strictly confidential and is covered by the relevant copyright and moral rights protections.

**Comment by djavco** [comment]
No further action required
