### ISSUE TITLE
Section name question

### ISSUE THREAD

**Issue by mrchristian** [consortium/traces_on_mcluhan#4]
Hi

Should the section be renamed, it looks like Larkin uses a apostrophe at the end.

So

EPILOGUE: THE FREEWHEEL' MARSHALL MCLUHAN

Instead of 

EPILOGUE: THE FREEWHEELING MARSHALL MCLUHAN

da da, http://mcluhan.gibraltarwalk.com/hybridvideo/index.html?s=4460

Thanks

S

**Comment by fabagit** [comment]
Hi 

Actually it should read:

Epilogue: THE FREEWHEELIN' MARSHALL McLUHAN

Yes please change this!
Thank you.

**Comment by fabagit** [comment]
Done

D

## 

Daniel Jackson

Avco Productions Ltd
13 Gibraltar Walk, London E2 7LH
http://www.avco.com http://www.avco.com/

Studio:  +44 (0)20 7613 0089
Mobile:  +44 (0) 7958 353 421
daniel@avco.com mailto:tina@avco.com

Avco Productions Limited is Registered in England No. 3401782

## All Information contained within this email and attached document(s) is for the attention of the addressee(s) only, is strictly confidential and is covered by the relevant copyright and moral rights protections.
