### ISSUE TITLE
citation link change

### ISSUE THREAD

**Issue by mrchristian** [consortium/traces_on_mcluhan#6]
Hi D,

Is it OK to change the hard link from the Gibraltar domain to https://mcluhan.consortium.io/hybridlecture/

https://github.com/consortium/hybrid-lecture-player/blob/master/hybridvideo/js/HybridVideo.js

Thanks

S

**Comment by djavco** [comment]
Do you just want me to redirect it there?

It’s not linked to Github or anything. I noticed consortium seemed to stop working earlier, I just thought maybe you were doing something.
atb

D

--
Daniel Jackson


Avco Productions Ltd
13 Gibraltar Walk, London E2 7LH
http://www.avco.com <http://www.avco.com/>

Studio:  +44 (0)20 7613 0089
Mobile:  +44 (0) 7958 353 421
daniel@avco.com <mailto:tina@avco.com>


Avco Productions Limited is Registered in England No. 3401782

All Information contained within this email and attached document(s) is for the attention of the addressee(s) only, is strictly confidential and is covered by the relevant copyright and moral rights protections.
--

**Comment by djavco** [comment]
Not sure really what you want to do. The gibraltar domain is not being used or updated now.

It's all here:
https://mcluhan.consortium.io/hybridlecture/

**Comment by djavco** [comment]
Changed
