### ISSUE TITLE
slides and captions going fast-forward

### ISSUE THREAD

**Issue by mrchristian** [consortium/traces_on_mcluhan#7]
On certain actions the player is running the slides and captions under the video in a fast-forwards mode. Meaning if I click on a section in the future in the YouTube slider, the image and text have to play though all the resources before it can arrive at the media for that future moment in time.

I can show you in a Skype screen share if needed.

Cheers

Simon

**Comment by djavco** [comment]
Yes youch just seen this. Will get back to you.

**Comment by djavco** [comment]
Looks like youtube 'onPlayerStateChange' is being missed (sometimes).

However these are the events that youtube triggers:
https://developers.google.com/youtube/iframe_api_reference

> onStateChange
> This event fires whenever the player's state changes. The data property of the event object that the API passes to your event listener function will specify an integer that corresponds to the new player state. Possible values are:
> -1 (unstarted)
> 0 (ended)
> 1 (playing)
> 2 (paused)
> 3 (buffering)
> 5 (video cued).

Not sure that any of these will necessarily be triggered when scrubbing the video

**Comment by djavco** [comment]
Fixed added check to see if we have advanced beyond the next slide.
