### ISSUE TITLE
hybridvideo.js changes not on dev deployment

### ISSUE THREAD

**Issue by mrchristian** [consortium/traces_on_mcluhan#8]
Hi,

Just wanted to note that my section descriptions have not been incorporated into latest dev deployment on mcluhan.consortium.io/hybridlecture/

d1fa50855a3441ed01ab1fcf82b4c765fe4270f1

I'm sure its just an oversight, but just wanted to note it.

S

**Comment by djavco** [comment]
Uploaded now
